Repository ExceptionTeam/mad-frontend, pull requests merged in 2018-07, with the labels that each got.

#12 change prefix app to exc
  angular.json
  src/app/app.component.ts
  src/tslint.json
Labels: when you have free time

#14 Feat/08/basic layout
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/layout-footer/layout-footer.component.html
  src/app/layout-footer/layout-footer.component.scss
  src/app/layout-footer/layout-footer.component.ts
  src/app/layout-header/layout-header.component.html
  src/app/layout-header/layout-header.component.scss
  src/app/layout-header/layout-header.component.ts
  src/app/layout-landing-page/layout-landing-page.component.html
  src/app/layout-landing-page/layout-landing-page.component.scss
  src/app/layout-landing-page/layout-landing-page.component.ts
  src/app/layout-navigation/layout-navigation.component.html
  src/app/layout-navigation/layout-navigation.component.scss
  src/app/layout-navigation/layout-navigation.component.ts
  src/app/layout-personal-menu/layout-personal-menu.component.html
  src/app/layout-personal-menu/layout-personal-menu.component.scss
  src/app/layout-personal-menu/layout-personal-menu.component.ts
  src/index.html
  src/styles.scss
Labels: frontend

#17 chore(08)changed scss of navigation
  src/app/layout-navigation/layout-navigation.component.scss
Labels: frontend

#20 Feat/15/all tasks teacher
  src/app/all-tasks-teacher/all-tasks-teacher.component.html
  src/app/all-tasks-teacher/all-tasks-teacher.component.scss
  src/app/all-tasks-teacher/all-tasks-teacher.component.ts
  src/app/app.module.ts
  src/app/layout-navigation/layout-navigation.component.html
  src/app/layout-navigation/layout-navigation.component.scss
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.scss
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
Labels: frontend

#31 Feat/19/assign a task
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/assign-a-task/assign-a-task.component.html
  src/app/assign-a-task/assign-a-task.component.scss
  src/app/assign-a-task/assign-a-task.component.ts
  src/app/select-student-or-group/select-student-or-group.component.html
  src/app/select-student-or-group/select-student-or-group.component.scss
  src/app/select-student-or-group/select-student-or-group.component.ts
  src/app/select-student-or-group/select-student-or-group.types.ts
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
Labels: frontend

#34 Feat/28/task full descr teacher
  src/app/all-tasks-teacher/all-tasks-teacher.component.ts
  src/app/app.module.ts
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.scss
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.ts
  src/app/task-full-descr-teacher/task-full-description.types.ts
Labels: frontend

#35 Fix/21/add button and pagination
  src/app/all-tasks-teacher/all-tasks-teacher.component.html
  src/app/all-tasks-teacher/all-tasks-teacher.component.scss
  src/app/all-tasks-teacher/all-tasks-teacher.component.ts
  src/app/allTasks.service.ts
  src/app/app.module.ts
  src/app/layout-footer/layout-footer.component.scss
  src/app/layout-landing-page/layout-landing-page.component.ts
  src/app/layout-navigation/layout-navigation.component.html
  src/app/layout-navigation/layout-navigation.component.scss
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.scss
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
  src/app/tasks.service.ts
Labels: frontend, when you have free time

#37 Rename some selectors
  src/app/all-tasks-teacher/all-tasks-teacher.component.scss
  src/app/app.component.html
  src/app/layout-footer/layout-footer.component.ts
  src/app/layout-header/layout-header.component.html
  src/app/layout-header/layout-header.component.ts
  src/app/layout-landing-page/layout-landing-page.component.html
  src/app/layout-landing-page/layout-landing-page.component.ts
  src/app/layout-navigation/layout-navigation.component.html
  src/app/layout-navigation/layout-navigation.component.scss
  src/app/layout-navigation/layout-navigation.component.ts
  src/app/layout-personal-menu/layout-personal-menu.component.html
  src/app/layout-personal-menu/layout-personal-menu.component.ts
Labels: frontend

#46 Feat/40/routing
  src/app/all-tasks-teacher/all-tasks-teacher.component.html
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/layout-header/layout-header.component.html
  src/app/layout-header/layout-header.component.ts
  src/app/layout-landing-page/layout-landing-page.component.html
  src/app/layout-landing-page/layout-landing-page.component.ts
  src/app/layout-landing-page/layout-landing-page.types.ts
  src/app/layout-navigation/layout-navigation.component.html
  src/app/layout-navigation/layout-navigation.component.ts
  src/app/layout-personal-menu/layout-personal-menu.component.html
  src/app/layout-personal-menu/layout-personal-menu.component.ts
  src/app/student-tasks-table/student-tasks-table.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
  src/app/task-creation-page/task-creation-page.component.html
  src/app/task-creation-page/task-creation-page.component.ts
  src/app/task-sending-page/task-sending-page.component.html
  src/app/task/task-routing.module.ts
  src/app/task/task.module.ts
Labels: frontend

#47 feat(27): combined components edit and create file
  src/app/InputOutputFiles.type.ts
  src/app/app.module.ts
  src/app/file-uploading/file-uploading.component.html
  src/app/file-uploading/file-uploading.component.scss
  src/app/file-uploading/file-uploading.component.ts
  src/app/input-output-adding/input-output-adding.component.html
  src/app/input-output-adding/input-output-adding.component.scss
  src/app/input-output-adding/input-output-adding.component.ts
  src/app/task-creation-page/task-creation-page.component.html
  src/app/task-creation-page/task-creation-page.component.ts
  src/app/task-edit-create-page/task-edit-create-page.component.html
  src/app/task-edit-create-page/task-edit-create-page.component.scss
  src/app/task-edit-create-page/task-edit-create-page.component.ts
Labels: frontend

#49 Feat(39): added separate modules for each feature
  src/app/app.module.ts
  src/app/assign-a-task/assigning-task.module.ts
  src/app/layout-navigation/layout.module.ts
  src/app/student-tasks-table/student-tasks.module.ts
  src/app/table-my-tasks-teacher/teacher-tasks.module.ts
  src/app/task-creation-page/task-creation.module.ts
  src/app/task-sending-page/task-sending.module.ts
Labels: frontend

#54 Fix/39/modules fixed
  src/app/app.module.ts
  src/app/assign-a-task/assigning-task.module.ts
  src/app/layout-navigation/layout.module.ts
  src/app/student-tasks-table/student-tasks-table.component.html
  src/app/student-tasks-table/student-tasks.module.ts
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/teacher-tasks.module.ts
  src/app/task-edit-create-page/task-edit-create-page.module.ts
  src/app/task-sending-page/task-sending-page.component.html
  src/app/task-sending-page/task-sending.module.ts
  src/app/task/task-routing.module.ts
Labels: bug, frontend

#52 Fix/44/refactor assign a task
  src/app/allTasks.service.ts
  src/app/app.module.ts
  src/app/assign-a-task/assign-a-task.component.html
  src/app/assign-a-task/assign-a-task.component.ts
  src/app/assign-a-task/assigning-task.module.ts
  src/app/select-student-or-group/select-student-or-group.component.html
  src/app/select-student-or-group/select-student-or-group.component.ts
  src/app/select-student-or-group/select-student-or-group.types.ts
  src/app/student-tasks-table/student-tasks.module.ts
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
  src/app/table-my-tasks-teacher/teacher-tasks.module.ts
  src/app/task-edit-create-page/task-edit-create-page.module.ts
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.scss
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.ts
  src/app/task/task-routing.module.ts
Labels: enhancement, frontend

#63 Fix/57/task full descr teacher
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.ts
Labels: frontend

#64 Fix/59/routing
  src/app/Types/InputOutputFiles.type.ts
  src/app/after-sending-task-page/after-sending-task-page.component.ts
  src/app/after-sending-task-page/after-sending-task.module.ts
  src/app/all-tasks-teacher/all-tasks-teacher.component.html
  src/app/app.module.ts
  src/app/assign-a-task/assign-a-task.component.ts
  src/app/assign-a-task/assigning-task.module.ts
  src/app/input-output-adding/input-output-adding.component.ts
  src/app/layout-landing-page/layout.module.ts
  src/app/layout-navigation/layout-navigation.component.ts
  src/app/student-tasks-table/student-tasks-table.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.html
  src/app/table-my-tasks-teacher/table-my-tasks-teacher.component.ts
  src/app/table-my-tasks-teacher/teacher-tasks.module.ts
  src/app/table-passed-tests-info/table-passed-tests-info.component.ts
  src/app/task-edit-create-page/TaskEditInfo.type.ts
  src/app/task-edit-create-page/task-edit-create-page.component.html
  src/app/task-edit-create-page/task-edit-create-page.component.ts
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher/task-full-descr-teacher.component.ts
  src/app/task-full-descr-teacher/task-full-description.types.ts
  src/app/task-sending-page/task-sending-page.component.html
  src/app/task-sending-page/task-sending-page.component.ts
  src/app/task-view-sending/task-view-sending.component.html
  src/app/task-view-sending/task-view-sending.component.ts
  src/app/task/task-routing.module.ts
  src/app/task/task.module.ts
  src/app/tasks.service.ts
Labels: frontend

#82 Fix/48/rename components
  src/app/all-tasks-teacher/all-tasks-teacher.component.ts
  src/app/file-uploading/file-uploading.component.html
  src/app/file-uploading/file-uploading.component.scss
  src/app/file-uploading/file-uploading.component.ts
  src/app/layout-landing-page/layout.module.ts
  src/app/task-after-sending-page/task-after-sending-page.component.html
  src/app/task-after-sending-page/task-after-sending-page.component.scss
  src/app/task-after-sending-page/task-after-sending-page.component.ts
  src/app/task-after-sending-page/task-after-sending-page.ts
  src/app/task-assigning-window/task-assigning-window.component.html
  src/app/task-assigning-window/task-assigning-window.component.scss
  src/app/task-assigning-window/task-assigning-window.component.ts
  src/app/task-assigning-window/task-assigning.module.ts
  src/app/task-edit-create-page/task-edit-create-page.component.html
  src/app/task-edit-create-page/task-edit-create-page.module.ts
  src/app/task-full-descr-teacher-page/full-description-page.module.ts
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.scss
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.ts
  src/app/task-full-descr-teacher-page/task-full-description.types.ts
  src/app/task-input-output-files/task-input-output-files.component.html
  src/app/task-input-output-files/task-input-output-files.component.scss
  src/app/task-input-output-files/task-input-output-files.component.ts
  src/app/task-passed-tests/task-passed-tests.component.html
  src/app/task-passed-tests/task-passed-tests.component.scss
  src/app/task-passed-tests/task-passed-tests.component.ts
  src/app/task-select-student-or-group/task-select-student-or-group.component.html
  src/app/task-select-student-or-group/task-select-student-or-group.component.scss
  src/app/task-select-student-or-group/task-select-student-or-group.component.ts
  src/app/task-select-student-or-group/task-select-student-or-group.types.ts
  src/app/task/task-routing.module.ts
  src/app/task/task.module.ts
  src/app/tasks-student-page/tasks-student-page.component.html
  src/app/tasks-student-page/tasks-student-page.component.scss
  src/app/tasks-student-page/tasks-student-page.component.ts
  src/app/tasks-student-page/tasks-student.module.ts
  src/app/tasks-table-teacher/tasks-table-teacher.component.html
  src/app/tasks-table-teacher/tasks-table-teacher.component.scss
  src/app/tasks-table-teacher/tasks-table-teacher.component.ts
  src/app/tasks-table-teacher/teacher-tasks.module.ts
  src/app/tasks-teacher-page/tasks-teacher-page.component.html
  src/app/tasks-teacher-page/tasks-teacher-page.component.scss
  src/app/tasks-teacher-page/tasks-teacher-page.component.ts
Labels: frontend

#78 Feat/69/req full descr teacher student
  src/app/Types/TaskFullDStudent.type.ts
  src/app/allTasksStudent.service.ts
  src/app/allTasksTeacher.service.ts
  src/app/app.module.ts
  src/app/file-uploading/file-uploading.component.html
  src/app/file-uploading/file-uploading.component.scss
  src/app/file-uploading/file-uploading.component.ts
  src/app/task-edit-create-page/task-edit-create-page.component.html
  src/app/task-edit-create-page/task-edit-create-page.component.ts
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.ts
  src/app/task-full-descr-teacher-page/task-full-description.types.ts
  src/app/task-sending-page/task-sending-page.component.html
  src/app/task-sending-page/task-sending-page.component.ts
  src/app/task-view-sending/task-view-sending.component.html
  src/app/task-view-sending/task-view-sending.component.ts
  src/app/task.service.ts
Labels: frontend

#90 Feat/86/req admin
  src/app/Types/TaskFullInfo.type.ts
  src/app/task-edit-create-page/task-edit-create-page.component.html
  src/app/task-edit-create-page/task-edit-create-page.component.ts
  src/app/task-edit-create-page/task-edit-create-page.module.ts
  src/app/task-full-descr-teacher-page/full-description-page.module.ts
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.html
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.scss
  src/app/task-full-descr-teacher-page/task-full-descr-teacher.component.ts
  src/app/task.service.ts
  src/app/tasks-table-teacher/teacher-tasks.module.ts
  src/app/tasks-teacher-page/tasks-teacher-page.component.html
Labels: enhancement, frontend

#93 Feat/91/sign in page
  src/app/app.module.ts
  src/app/layout-header/layout-header.component.html
  src/app/layout-header/layout-header.component.scss
  src/app/layout-landing-page/layout.module.ts
  src/app/sign-in-page/sign-in-page.component.html
  src/app/sign-in-page/sign-in-page.component.scss
  src/app/sign-in-page/sign-in-page.component.ts
  src/app/sign-in-page/sign-in.module.ts
Labels: frontend

#98 feat(89): add registration-page component
  src/app/registration-page/registration-page.component.html
  src/app/registration-page/registration-page.component.scss
  src/app/registration-page/registration-page.component.ts
  src/app/registration-page/registration-page.module.ts
  src/app/task/task-routing.module.ts
  src/app/task/task.module.ts
Labels: frontend

#97 Feat/96/edit password page
  src/app/app-routing.module.ts
  src/app/forgot-password/forgot-password.component.html
  src/app/forgot-password/forgot-password.component.scss
  src/app/forgot-password/forgot-password.component.ts
  src/app/forgot-password/forgot-password.module.ts
  src/app/layout-landing-page/layout.module.ts
  src/app/sign-in-page/sign-in-page.component.html
  src/app/sign-in-page/sign-in-page.component.scss
  src/app/sign-in-page/sign-in.module.ts
  src/app/task/task-routing.module.ts
Labels: frontend

#102 Feat/92/main page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/forgot-password/forgot-password.component.html
  src/app/forgot-password/forgot-password.component.scss
  src/app/home-page/home-page-routing.module.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.scss
  src/app/home-page/home-page.component.ts
  src/app/home-page/home-page.module.ts
  src/app/layout-header/layout-header.component.html
  src/app/layout-header/layout-header.component.scss
  src/app/sign-in-page/sign-in-page.component.html
  src/app/sign-in-page/sign-in-page.component.scss
  src/app/task/task.module.ts
Labels: frontend

#104 Feat/103/routing registration
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/layout-landing-page/layout.module.ts
  src/app/registration-authorization/registration-authorization-routing.module.ts
  src/app/registration-authorization/registration-authorization.module.ts
  src/app/task/task.module.ts
Labels: frontend
